"""
SFT Trainer
Provides configuration and launch scripts for fine-tuning models
on collected DevOps-MAS data using LoRA/QLoRA.
"""

import json
import logging
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)


class SFTTrainer:
    """
    Generates training configs and launch commands for SFT.
    Supports: Hugging Face Trainer, LLaMA-Factory, Axolotl.
    """

    def __init__(self, data_dir: str = "data/sft"):
        self.data_dir = Path(data_dir)

    def generate_training_config(
        self,
        base_model: str = "Qwen/Qwen2.5-3B-Instruct",
        dataset_path: Optional[str] = None,
        output_dir: str = "outputs/sft_model",
        method: str = "lora",
        num_epochs: int = 3,
        learning_rate: float = 2e-4,
        batch_size: int = 4,
        max_seq_length: int = 2048,
        lora_rank: int = 16,
        lora_alpha: int = 32,
    ) -> Dict[str, Any]:
        """Generate a training config compatible with common frameworks."""
        if dataset_path is None:
            dataset_path = str(self.data_dir / "sft_dataset_alpaca.json")

        config = {
            "model_name_or_path": base_model,
            "dataset": dataset_path,
            "output_dir": output_dir,
            "finetuning_type": method,
            "num_train_epochs": num_epochs,
            "learning_rate": learning_rate,
            "per_device_train_batch_size": batch_size,
            "max_seq_length": max_seq_length,
            "gradient_accumulation_steps": 4,
            "warmup_ratio": 0.1,
            "logging_steps": 10,
            "save_steps": 100,
            "fp16": True,
            "lora_rank": lora_rank,
            "lora_alpha": lora_alpha,
            "lora_dropout": 0.05,
            "lora_target": "q_proj,v_proj,k_proj,o_proj",
            "template": "qwen",
            "cutoff_len": max_seq_length,
        }

        config_path = self.data_dir / "training_config.json"
        with open(config_path, "w", encoding="utf-8") as f:
            json.dump(config, f, indent=2, ensure_ascii=False)

        logger.info(f"Training config saved to {config_path}")
        return config

    def generate_launch_script(self, config_path: Optional[str] = None) -> str:
        """Generate a shell script to launch training."""
        if config_path is None:
            config_path = str(self.data_dir / "training_config.json")

        script = f"""#!/bin/bash
# DevOps-MAS SFT Training Script
# Generated by SFTTrainer

set -e

echo "=== DevOps-MAS SFT Training ==="
echo "Config: {config_path}"

# Option 1: Using LLaMA-Factory (recommended)
if command -v llamafactory-cli &> /dev/null; then
    echo "Using LLaMA-Factory..."
    llamafactory-cli train {config_path}
    exit 0
fi

# Option 2: Using Hugging Face Trainer directly
echo "Using Hugging Face Trainer..."
python -c "
import json
from transformers import (
    AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
)
from peft import LoraConfig, get_peft_model, TaskType
from datasets import load_dataset

with open('{config_path}') as f:
    cfg = json.load(f)

tokenizer = AutoTokenizer.from_pretrained(cfg['model_name_or_path'], trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(
    cfg['model_name_or_path'], trust_remote_code=True, torch_dtype='auto'
)

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=cfg.get('lora_rank', 16),
    lora_alpha=cfg.get('lora_alpha', 32),
    lora_dropout=cfg.get('lora_dropout', 0.05),
    target_modules=cfg.get('lora_target', 'q_proj,v_proj').split(','),
)
model = get_peft_model(model, lora_config)

dataset = load_dataset('json', data_files=cfg['dataset'])

training_args = TrainingArguments(
    output_dir=cfg['output_dir'],
    num_train_epochs=cfg['num_train_epochs'],
    per_device_train_batch_size=cfg['per_device_train_batch_size'],
    learning_rate=cfg['learning_rate'],
    fp16=cfg.get('fp16', True),
    logging_steps=cfg.get('logging_steps', 10),
    save_steps=cfg.get('save_steps', 100),
    warmup_ratio=cfg.get('warmup_ratio', 0.1),
)

trainer = Trainer(model=model, args=training_args, train_dataset=dataset['train'], tokenizer=tokenizer)
trainer.train()
trainer.save_model()
print('Training complete!')
"

echo "=== Training Complete ==="
"""
        script_path = self.data_dir / "train.sh"
        with open(script_path, "w") as f:
            f.write(script)

        logger.info(f"Training script saved to {script_path}")
        return str(script_path)

    def get_recommended_configs(self) -> Dict[str, Dict[str, Any]]:
        """Return recommended configs for different scenarios."""
        return {
            "quick_finetune": {
                "description": "Quick LoRA fine-tune on small model (< 1 hour on single GPU)",
                "base_model": "Qwen/Qwen2.5-3B-Instruct",
                "method": "lora",
                "epochs": 3,
                "batch_size": 4,
                "lora_rank": 8,
            },
            "quality_finetune": {
                "description": "Higher quality fine-tune with larger LoRA rank",
                "base_model": "Qwen/Qwen2.5-7B-Instruct",
                "method": "lora",
                "epochs": 5,
                "batch_size": 2,
                "lora_rank": 32,
            },
            "qlora_efficient": {
                "description": "Memory-efficient QLoRA for limited GPU resources",
                "base_model": "Qwen/Qwen2.5-7B-Instruct",
                "method": "qlora",
                "epochs": 3,
                "batch_size": 2,
                "lora_rank": 16,
            },
        }
